version: 2
registries:
  npm-github:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: ${{secrets.READER_TOKEN}}
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    registries:
      - npm-github
    cooldown:
      default-days: 7
    groups:
      navikt:
        patterns:
          - "@navikt/*"
      react:
        patterns:
          - "react"
          - "react-dom"
          - "react-hook-form"
          - "react-markdown"
          - "remark-gfm"
          - "@hookform/resolvers"
          - "@types/react"
          - "@types/react-dom"
          - "framer-motion"
      next:
        patterns:
          - "next"
          - "next-*"
          - "@next/*"
          - "@mdx-js/*"
          - "eslint-config-next"
      npm:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    groups:
      github-actions:
        patterns:
          - "*"