name: Build, push, and deploy

on:
  push:

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 22.x
          registry-url: https://npm.pkg.github.com
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

      - name: Build application
        run: npm run build

      - name: Push docker image to GAR
        uses: nais/docker-build-push@2d2b0a7193e65422b7f0355d4afb445e0a8b2cc3
        id: docker-build-push
        with:
          team: delta

  deploy:
    name: Deploy to NAIS
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais-dev.yaml
          IMAGE: ${{ needs.build.outputs.image }}
      - uses: nais/deploy/actions/deploy@2d18f050f07b6a007864c6a57070ed915d571beb
        if: github.ref == 'refs/heads/main'
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais-prod.yaml
          IMAGE: ${{ needs.build.outputs.image }}

  trivy:
    name: Scan Docker image with Trivy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      security-events: write
      id-token: write
      actions: read # require for non-public repos
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: false
      - uses: nais/login@bb6c3e1e14e53d40d69d0d092bd2fce2e39ae3bf
        with:
          team: delta
      - name: Scan docker image for secrets
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25
        with:
          image-ref: '${{ needs.build.outputs.image }}'
          format: 'sarif'
          scanners: 'secret'
          output: 'trivy.sarif'
      - uses: github/codeql-action/upload-sarif@d1ba80a13dd99fba24a470575428917156a28b43
        with:
          sarif_file: 'trivy.sarif'
